## Stage 1 : build with maven
FROM quay.io/quarkus/centos-quarkus-maven:21.0.0-java11 AS build
COPY ./invoice-generator /tmp/my-project
USER root
RUN chown -R quarkus /tmp/my-project
USER quarkus
# we skip tests here. Tests are executed in a previous step (outside docker). See github actions witin this project.
RUN mvn -f /tmp/my-project/pom.xml clean package -DskipTests


## Stage 2 : create a lambda image
# (1)
FROM public.ecr.aws/lambda/java:11

ARG APP_NAME=invoice-generator
ARG APP_VERSION=1.0-SNAPSHOT

WORKDIR /var/task/lib/
COPY --from=build /tmp/my-project/target/lib /var/task/lib
COPY --from=build /tmp/my-project/target/*-runner.jar /var/task/lib/application.jar

# (3) Setting the command to the Quarkus lambda handler
CMD ["io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest"]

