/*
 * This file is generated by jOOQ.
 */
package com.gmail.pzalejko.invoice.manager.db.tables;


import com.gmail.pzalejko.invoice.manager.db.Keys;
import com.gmail.pzalejko.invoice.manager.db.Public;
import com.gmail.pzalejko.invoice.manager.db.tables.records.CompanyAddressRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyAddress extends TableImpl<CompanyAddressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.company_address</code>
     */
    public static final CompanyAddress COMPANY_ADDRESS = new CompanyAddress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CompanyAddressRecord> getRecordType() {
        return CompanyAddressRecord.class;
    }

    /**
     * The column <code>public.company_address.id</code>.
     */
    public final TableField<CompanyAddressRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.company_address.street</code>.
     */
    public final TableField<CompanyAddressRecord, String> STREET = createField(DSL.name("street"), SQLDataType.VARCHAR(25).nullable(false), this, "");

    /**
     * The column <code>public.company_address.number</code>.
     */
    public final TableField<CompanyAddressRecord, String> NUMBER = createField(DSL.name("number"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>public.company_address.zip</code>.
     */
    public final TableField<CompanyAddressRecord, String> ZIP = createField(DSL.name("zip"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>public.company_address.city</code>.
     */
    public final TableField<CompanyAddressRecord, String> CITY = createField(DSL.name("city"), SQLDataType.VARCHAR(25).nullable(false), this, "");

    /**
     * The column <code>public.company_address.country</code>.
     */
    public final TableField<CompanyAddressRecord, String> COUNTRY = createField(DSL.name("country"), SQLDataType.VARCHAR(25).nullable(false), this, "");

    private CompanyAddress(Name alias, Table<CompanyAddressRecord> aliased) {
        this(alias, aliased, null);
    }

    private CompanyAddress(Name alias, Table<CompanyAddressRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.company_address</code> table reference
     */
    public CompanyAddress(String alias) {
        this(DSL.name(alias), COMPANY_ADDRESS);
    }

    /**
     * Create an aliased <code>public.company_address</code> table reference
     */
    public CompanyAddress(Name alias) {
        this(alias, COMPANY_ADDRESS);
    }

    /**
     * Create a <code>public.company_address</code> table reference
     */
    public CompanyAddress() {
        this(DSL.name("company_address"), null);
    }

    public <O extends Record> CompanyAddress(Table<O> child, ForeignKey<O, CompanyAddressRecord> key) {
        super(child, key, COMPANY_ADDRESS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CompanyAddressRecord, Integer> getIdentity() {
        return (Identity<CompanyAddressRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<CompanyAddressRecord> getPrimaryKey() {
        return Keys.COMPANY_ADDRESS_PKEY;
    }

    @Override
    public CompanyAddress as(String alias) {
        return new CompanyAddress(DSL.name(alias), this);
    }

    @Override
    public CompanyAddress as(Name alias) {
        return new CompanyAddress(alias, this);
    }

    @Override
    public CompanyAddress as(Table<?> alias) {
        return new CompanyAddress(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CompanyAddress rename(String name) {
        return new CompanyAddress(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CompanyAddress rename(Name name) {
        return new CompanyAddress(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CompanyAddress rename(Table<?> name) {
        return new CompanyAddress(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Integer, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Integer, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
