# https://docs.aws.amazon.com/codebuild/latest/userguide/cloudformation-vpc-template.html
AWSTemplateFormatVersion: "2010-09-09"
Description: Application setup via AWS Cloud Formation
Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: invoiceApp

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.0.0.0/16

  PublicSubCIDR:
    Description: Please enter the IP range (CIDR notation) for this public subnet
    Type: String
    Default: 10.0.1.0/24

Resources:
  #VPC
  AppVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: dedicated
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  AppVpcRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AppVpc
    Properties:
      VpcId:
        Ref: AppVpc
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Routes

  AppInternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: AppVpcRouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: AppVpc
      InternetGatewayId:
        Ref: AppInternetGateway

  AppInternetRoute:
    Type: AWS::EC2::Route
    DependsOn: AppInternetGateway
    Properties:
      RouteTableId:
        Ref: AppVpcRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: AppInternetGateway

  AppPubSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: AppVpc
      CidrBlock: !Ref PublicSubCIDR
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public subnet

  AppPubSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: AppPubSubnet
      RouteTableId:
        Ref: AppVpcRouteTable