/*
 * This file is generated by jOOQ.
 */
package com.gmail.pzalejko.invoice.manager.db.tables.records;


import com.gmail.pzalejko.invoice.manager.db.tables.CompanyAddress;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyAddressRecord extends UpdatableRecordImpl<CompanyAddressRecord> implements Record6<Integer, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.company_address.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.company_address.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.company_address.street</code>.
     */
    public void setStreet(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.company_address.street</code>.
     */
    public String getStreet() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.company_address.number</code>.
     */
    public void setNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.company_address.number</code>.
     */
    public String getNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.company_address.zip</code>.
     */
    public void setZip(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.company_address.zip</code>.
     */
    public String getZip() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.company_address.city</code>.
     */
    public void setCity(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.company_address.city</code>.
     */
    public String getCity() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.company_address.country</code>.
     */
    public void setCountry(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.company_address.country</code>.
     */
    public String getCountry() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CompanyAddress.COMPANY_ADDRESS.ID;
    }

    @Override
    public Field<String> field2() {
        return CompanyAddress.COMPANY_ADDRESS.STREET;
    }

    @Override
    public Field<String> field3() {
        return CompanyAddress.COMPANY_ADDRESS.NUMBER;
    }

    @Override
    public Field<String> field4() {
        return CompanyAddress.COMPANY_ADDRESS.ZIP;
    }

    @Override
    public Field<String> field5() {
        return CompanyAddress.COMPANY_ADDRESS.CITY;
    }

    @Override
    public Field<String> field6() {
        return CompanyAddress.COMPANY_ADDRESS.COUNTRY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getStreet();
    }

    @Override
    public String component3() {
        return getNumber();
    }

    @Override
    public String component4() {
        return getZip();
    }

    @Override
    public String component5() {
        return getCity();
    }

    @Override
    public String component6() {
        return getCountry();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getStreet();
    }

    @Override
    public String value3() {
        return getNumber();
    }

    @Override
    public String value4() {
        return getZip();
    }

    @Override
    public String value5() {
        return getCity();
    }

    @Override
    public String value6() {
        return getCountry();
    }

    @Override
    public CompanyAddressRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CompanyAddressRecord value2(String value) {
        setStreet(value);
        return this;
    }

    @Override
    public CompanyAddressRecord value3(String value) {
        setNumber(value);
        return this;
    }

    @Override
    public CompanyAddressRecord value4(String value) {
        setZip(value);
        return this;
    }

    @Override
    public CompanyAddressRecord value5(String value) {
        setCity(value);
        return this;
    }

    @Override
    public CompanyAddressRecord value6(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public CompanyAddressRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanyAddressRecord
     */
    public CompanyAddressRecord() {
        super(CompanyAddress.COMPANY_ADDRESS);
    }

    /**
     * Create a detached, initialised CompanyAddressRecord
     */
    public CompanyAddressRecord(Integer id, String street, String number, String zip, String city, String country) {
        super(CompanyAddress.COMPANY_ADDRESS);

        setId(id);
        setStreet(street);
        setNumber(number);
        setZip(zip);
        setCity(city);
        setCountry(country);
    }
}
