/*
 * This file is generated by jOOQ.
 */
package com.gmail.pzalejko.invoice.manager.db.tables.records;


import com.gmail.pzalejko.invoice.manager.db.enums.ItemUnit;
import com.gmail.pzalejko.invoice.manager.db.tables.Invoiceitem;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoiceitemRecord extends UpdatableRecordImpl<InvoiceitemRecord> implements Record9<Integer, Integer, Integer, String, ItemUnit, Integer, BigDecimal, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.invoiceitem.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.invoiceitem.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.invoiceitem.item_id</code>.
     */
    public void setItemId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.invoiceitem.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.invoiceitem.invoice_id</code>.
     */
    public void setInvoiceId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.invoiceitem.invoice_id</code>.
     */
    public Integer getInvoiceId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.invoiceitem.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.invoiceitem.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.invoiceitem.unit</code>.
     */
    public void setUnit(ItemUnit value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.invoiceitem.unit</code>.
     */
    public ItemUnit getUnit() {
        return (ItemUnit) get(4);
    }

    /**
     * Setter for <code>public.invoiceitem.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.invoiceitem.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.invoiceitem.price_value</code>.
     */
    public void setPriceValue(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.invoiceitem.price_value</code>.
     */
    public BigDecimal getPriceValue() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.invoiceitem.price_vat</code>.
     */
    public void setPriceVat(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.invoiceitem.price_vat</code>.
     */
    public Integer getPriceVat() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.invoiceitem.price_currency</code>.
     */
    public void setPriceCurrency(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.invoiceitem.price_currency</code>.
     */
    public String getPriceCurrency() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, Integer, String, ItemUnit, Integer, BigDecimal, Integer, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Integer, Integer, String, ItemUnit, Integer, BigDecimal, Integer, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Invoiceitem.INVOICEITEM.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Invoiceitem.INVOICEITEM.ITEM_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Invoiceitem.INVOICEITEM.INVOICE_ID;
    }

    @Override
    public Field<String> field4() {
        return Invoiceitem.INVOICEITEM.NAME;
    }

    @Override
    public Field<ItemUnit> field5() {
        return Invoiceitem.INVOICEITEM.UNIT;
    }

    @Override
    public Field<Integer> field6() {
        return Invoiceitem.INVOICEITEM.QUANTITY;
    }

    @Override
    public Field<BigDecimal> field7() {
        return Invoiceitem.INVOICEITEM.PRICE_VALUE;
    }

    @Override
    public Field<Integer> field8() {
        return Invoiceitem.INVOICEITEM.PRICE_VAT;
    }

    @Override
    public Field<String> field9() {
        return Invoiceitem.INVOICEITEM.PRICE_CURRENCY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getItemId();
    }

    @Override
    public Integer component3() {
        return getInvoiceId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public ItemUnit component5() {
        return getUnit();
    }

    @Override
    public Integer component6() {
        return getQuantity();
    }

    @Override
    public BigDecimal component7() {
        return getPriceValue();
    }

    @Override
    public Integer component8() {
        return getPriceVat();
    }

    @Override
    public String component9() {
        return getPriceCurrency();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getItemId();
    }

    @Override
    public Integer value3() {
        return getInvoiceId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public ItemUnit value5() {
        return getUnit();
    }

    @Override
    public Integer value6() {
        return getQuantity();
    }

    @Override
    public BigDecimal value7() {
        return getPriceValue();
    }

    @Override
    public Integer value8() {
        return getPriceVat();
    }

    @Override
    public String value9() {
        return getPriceCurrency();
    }

    @Override
    public InvoiceitemRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public InvoiceitemRecord value2(Integer value) {
        setItemId(value);
        return this;
    }

    @Override
    public InvoiceitemRecord value3(Integer value) {
        setInvoiceId(value);
        return this;
    }

    @Override
    public InvoiceitemRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public InvoiceitemRecord value5(ItemUnit value) {
        setUnit(value);
        return this;
    }

    @Override
    public InvoiceitemRecord value6(Integer value) {
        setQuantity(value);
        return this;
    }

    @Override
    public InvoiceitemRecord value7(BigDecimal value) {
        setPriceValue(value);
        return this;
    }

    @Override
    public InvoiceitemRecord value8(Integer value) {
        setPriceVat(value);
        return this;
    }

    @Override
    public InvoiceitemRecord value9(String value) {
        setPriceCurrency(value);
        return this;
    }

    @Override
    public InvoiceitemRecord values(Integer value1, Integer value2, Integer value3, String value4, ItemUnit value5, Integer value6, BigDecimal value7, Integer value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoiceitemRecord
     */
    public InvoiceitemRecord() {
        super(Invoiceitem.INVOICEITEM);
    }

    /**
     * Create a detached, initialised InvoiceitemRecord
     */
    public InvoiceitemRecord(Integer id, Integer itemId, Integer invoiceId, String name, ItemUnit unit, Integer quantity, BigDecimal priceValue, Integer priceVat, String priceCurrency) {
        super(Invoiceitem.INVOICEITEM);

        setId(id);
        setItemId(itemId);
        setInvoiceId(invoiceId);
        setName(name);
        setUnit(unit);
        setQuantity(quantity);
        setPriceValue(priceValue);
        setPriceVat(priceVat);
        setPriceCurrency(priceCurrency);
    }
}
