/**
 * Sub-domain handling invoice requests i.e. requesting for a new invoice generation. As a result of the request, a new
 * invoice file will be generated by the system. What's more, the invoice can be viewed and downloaded. But this part
 * is not in the scope of this sub-domain/context.
 */
package com.gmail.pzalejko.invoice.invoicerequest;