name: ci

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - 
        name: Run the Maven verify phase for the web project
        run: mvn -f web/pom.xml clean verify
      - 
        name: Run the Maven verify phase for invoice generator project
        run: mvn -f invoice-generator/pom.xml clean verify
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_API_KEY }}
      -
        name: Build and push the web project
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile_web
          push: true
          tags: |
            pzalejko/ddd-invoice-web:latest
      -
        name: Build and push the invoice generator project
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile_invoiceGenerator
          push: true
          tags: |
            pzalejko/ddd-invoice-generator:latest
